# Generated by Django 6.0.3 on 2026-04-01 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ames_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='corsa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='ames_api.corsa'),
            preserve_default=False,
        ),
    ]
